# Generated by Django 5.1.4 on 2025-01-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='upload_to',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='views',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='content/images/'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
