# Generated by Django 5.1.4 on 2025-01-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_blogmodel_created_at_remove_blogmodel_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='file_directory',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
