# Generated by Django 5.1.1 on 2025-04-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_blogmodel_file_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='exampleSite/static/example'),
        ),
    ]
